### ISSUE TITLE
Doesnt work in latest minecraft

### ISSUE THREAD

**Issue by Snid0** [Llama-Studios/mobile-export#4]
Hello, firstly thank you for creating this pack, it has allowed me to back up my sons minecraft worlds from his amazon tablet many times previously.

I recently tried to use it on a newer version of minecraft and the export button is not there!

Any help would be appreciated!

**Comment by kyleplo** [comment]
Unfortunately with the recent changes to Minecraft, this pack no longer works, and as far as I am aware there isn't anything that I can do to fix it.
If you just need local backups, making a copy the world should suffice. If you need to back them up to another device, I don't have a Kindle so I'm not entirely sure how it works but I believe it is possible to access the internal storage and find the world save data to back up.
